[build]
  publish = "."
  functions = "netlify/functions"
[build.environment]
  NODE_VERSION = "18"
  GPS_ANCHOR = "PIK Jakarta Utara, Indonesia"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"], Country = ["!US"]}

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "max-age=31536000"

# API function settings
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Environment variables (set these in Netlify dashboard instead)
# [build.environment]
#   GOOGLE_MAPS_API_KEY = "your-key-here"
#   DEEPSEEK_API_KEY = "your-key-here"
